### ISSUE TITLE
Bug: "enabled" and "loadScript"options are always true

### ISSUE THREAD

**Issue by shatskiy** [gtm-support/core#135]
## Info

| Tool    | Version       |
| ------- | ------------- |
| Package | v1.1.0        |

## Description

Options "enabled" and "loadScript" are always set to true independently of the passed configuration.

See:
https://github.com/gtm-support/core/blob/c4bbbe51783f33aea3ce187f4463533a5353b315/src/gtm-support.ts#L49-L56

Was this done on purpose maybe? Or what's the point?

**Comment by Shinigami92** [comment]
I don't understand :thinking: 

https://github.com/gtm-support/core/blob/c4bbbe51783f33aea3ce187f4463533a5353b315/src/gtm-support.ts#L55

This would override `enabled` or `loadScript` unless the given options doesn't contains the keys

**Comment by shatskiy** [comment]
@Shinigami92,

I've investigated. It was my bad. Please disregard and delete this issue as mistaken.

p.s. My issue was that I used 'enable' instead of 'enabled' and couldn't recognize my mistake. My apologize.
