### ISSUE TITLE
Support for adding custom data-attributes & classes to the initialisation script tag

### ISSUE THREAD

**Issue by Reiss-Cashmore** [gtm-support/core#186]
## Request / Idea
I have a very stubborn 3rd Party Cookie Consent banner which relies of certain data-attributes being present on the script tags in order to allow / block them based on user responses to the consent banner.

Is there a way to add some custom HTML data-attributes & classes to the script tag that initialises the GTM script? In a nice way using the configuration object?

If I were to create an PR for this, is it likely to be accepted?

## Additional Context

They want me to inject tags like this if I were using a conventional GTM initialisation snippet

```
j.setAttributeNode(d.createAttribute('data-ot-ignore'));
j.setAttribute('class','optanon-category-C0001');
```

To produce something like this

`<script src="https://www.googletagmanager.com/gtm.js" data-ot-ignore class="optanon-category-C0001"></script>`

**Comment by Shinigami92** [comment]
Maybe we can somehow support an exposed function to get the script element, then you can add and remove stuff as you want
