### ISSUE TITLE
`trackEvent` data without predefined values

### ISSUE THREAD

**Issue by lukasaric** [gtm-support/core#351]
@Shinigami92 
## Request / Idea

The proposal is to add an option or something similar to the `trackEvent` function so that we can have raw/pure custom data sent to the data layer.

Something like:

```ts
gtm.trackEvent({ custom: 'test' }, { raw: true })
// object in data layer will be: { custom: 'test' }
```

This can be achieved if we use `dataLayer` directly, but I think it would be nice to have the option already here since we also have logging here if debug is enabled.

Also, one more question, what's the reasoning behind in the first place why the defaults are set?

## Additional Context

Currently `trackEvent` has some prefined values (event, value etc) already set (prefined values are set within [here](https://github.com/gtm-support/core/blob/1ddebc22ade4dc0367a885630bb5689364f7456f/src/gtm-support.ts#L213C13-L213C13)).

Example:
```ts
gtm.trackEvent({ custom: 'test' })
// object in data layer will be: { custom: 'test', event: null, value: null …. }
```
...

Futhermore, first thread started within the [nuxt-gtm module](https://github.com/zadigetvoltaire/nuxt-gtm/issues/12)

**Comment by Shinigami92** [comment]
> Also, one more question, what's the reasoning behind in the first place why the defaults are set?

I would love to forward this question to @mib200, because it was always like this, the last 7 years

https://github.com/mib200/vue-gtm/commit/47e53145f6b8e8b7236beb59078d7e7b0fb3b6ff#diff-d6f975ceab5e8c813a5cc2627408ad9366bf607e4fe314dc1eab96b1eb450140R17-R35

I don't even know Google Tag Manager! So an introduction what these values are and what they are doing would be really helpful for me.
Right now in this point of time, I'm by far to afraid to touch that code and don't want to break stuff that is related with it, because I'm not the original author of this lib.

Maybe it would be even better right now to just add a `trackEvent_v2` function 😆 (or another better name...)

**Comment by lukasaric** [comment]
> > Also, one more question, what's the reasoning behind in the first place why the defaults are set?
> 
> I would love to forward this question to @mib200, because it was always like this, the last 7 years
> 
> [mib200/vue-gtm@47e5314#diff-d6f975ceab5e8c813a5cc2627408ad9366bf607e4fe314dc1eab96b1eb450140R17-R35](https://github.com/mib200/vue-gtm/commit/47e53145f6b8e8b7236beb59078d7e7b0fb3b6ff#diff-d6f975ceab5e8c813a5cc2627408ad9366bf607e4fe314dc1eab96b1eb450140R17-R35)
> 
> I don't even know Google Tag Manager! So an introduction what these values are and what they are doing would be really helpful for me. Right now in this point of time, I'm by far to afraid to touch that code and don't want to break stuff that is related with it, because I'm not the original author of this lib.
> 
> Maybe it would be even better right now to just add a `trackEvent_v2` function 😆 (or another better name...)

Well, I also agree. Maybe we can just add the same functionallity as in nuxt 2 gtm:
https://www.npmjs.com/package/@nuxtjs/gtm

Basically directly pushing data ti the datalayer and then just add the debug mode there also

**Comment by Shinigami92** [comment]
You mean this gtm.push?
Sounds good to me

**Comment by lukasaric** [comment]
> You mean this gtm.push?
> Sounds good to me

Yes

**Comment by Shinigami92** [comment]
> > You mean this gtm.push?
> > Sounds good to me
> 
> Yes

you have green light to start the PR 🙂

**Comment by lukasaric** [comment]
> > > You mean this gtm.push?
> > > Sounds good to me
> > 
> > 
> > Yes
> 
> you have green light to start the PR 🙂

Nice! Will do that as soon as I find some time!

**Comment by lukasaric** [comment]
> > > You mean this gtm.push?
> > > Sounds good to me
> > 
> > 
> > Yes
> 
> you have green light to start the PR 🙂

Here's the PR :) 
https://github.com/gtm-support/core/pull/352

**Comment by lukasaric** [comment]
@Shinigami92 fyi, can you bump the vue-grm core version with this new change?

**Comment by Shinigami92** [comment]
> @Shinigami92 fyi, can you bump the vue-gtm core version with this new change and release it?

Is https://www.npmjs.com/package/@gtm-support/core/v/2.2.0 not working for you?

**Comment by Shinigami92** [comment]
And if you mean the vue-gtm ... just recreate your lock file and/or node_modules

**Comment by lukasaric** [comment]
> And if you mean the vue-gtm ... just recreate your lock file and/or node_modules

Hmm, I’m using the vue-gtm, but it does not have the latest core as far as I can see (curre ny is 2.0.0)

**Comment by Shinigami92** [comment]
But it's `^2.0.0`

https://github.com/gtm-support/vue-gtm/blob/9b54f13c9f63ecbf920e3072d516d7be91bc9626/package.json#L70

This should resolve to:
<img src="https://github.com/gtm-support/core/assets/7195563/364b81f5-1772-4819-b09c-acad3cb478bc" width="400px" />

https://semver.npmjs.com/

**Comment by lukasaric** [comment]
> https://github.com/gtm-support/vue-gtm/blob/9b54f13c9f63ecbf920e3072d516d7be91bc9626/package.json#L70

nvm, completely misread it :facepalm: it's all fine. Thansk!
