### ISSUE TITLE
Support for the event when the script is loaded.

### ISSUE THREAD

**Issue by negezor** [gtm-support/core#77]
Sometimes there is a need to perform an action after we know exactly when the script is loaded.

**Comment by Shinigami92** [comment]
I think we would need to trigger an event after this line

https://github.com/gtm-support/core/blob/d7efd7c1f51a4d70b720e31f627f59239188c745/src/utils.ts#L61

Do you have an idea how we could do this?
Are you interested in creating and drafting a PR?

**Comment by negezor** [comment]
The script will only be added by the DOM, but it may not be loaded and executed. Need to add callback to `script.onload`. And then forward it to the top, like:
```ts
app.use(
  createGtm({
    onReady() {
      // Loaded
    }
  })
);
```

I think it would be possible to do something for the Composition API:
```ts
import { onReady } from '@gtm-support/vue-gtm';

//...

setup() {
  onReady(() => {
    // Do something
  });
}
```

**Comment by Shinigami92** [comment]
Yeah sounds good, I will think about it and may work on that on weekend if I find time

**Comment by Shinigami92** [comment]
@negezor 
Hope it's okay if I delay the release a bit, maybe I will release tomorrow or monday. Would this be okay for you? Or do you need it now?

**Comment by negezor** [comment]
No problem, I'm in no hurry.
